### PR TITLE
add subunit

### PR DESCRIPTION
**Pull request by getong**

### CODE REVIEW

**Comment by getong** [comment]
See libcheck/check#60
In Debian 9 stretch, this error happens.

**Comment by mocchira** [comment]
@getong We've already dealt with the subunit dependency by https://github.com/leo-project/libcutil/blob/develop/CMakeModules/FindSubunit.cmake that will add the linker flag subunit  if it's installed on the platform.

**Comment by getong** [comment]
@mocchira  Not the driver code, it is the test code error. 
```
[ 50%] Built target cutil
[ 58%] Linking C executable test_suites
/usr/lib/gcc/x86_64-linux-gnu/6/../../../x86_64-linux-gnu/libcheck.a(check_log.o): In function `subunit_lfun':
(.text+0x5f4): undefined reference to `subunit_test_start'
/usr/lib/gcc/x86_64-linux-gnu/6/../../../x86_64-linux-gnu/libcheck.a(check_log.o): In function `subunit_lfun':
(.text+0x6bf): undefined reference to `subunit_test_fail'
/usr/lib/gcc/x86_64-linux-gnu/6/../../../x86_64-linux-gnu/libcheck.a(check_log.o): In function `subunit_lfun':
(.text+0x6d4): undefined reference to `subunit_test_pass'
/usr/lib/gcc/x86_64-linux-gnu/6/../../../x86_64-linux-gnu/libcheck.a(check_log.o): In function `subunit_lfun':
(.text+0x6ef): undefined reference to `subunit_test_error'
collect2: error: ld returned 1 exit status
tests/CMakeFiles/test_suites.dir/build.make:200: recipe for target 'tests/test_suites' failed
make[2]: *** [tests/test_suites] Error 1
CMakeFiles/Makefile2:140: recipe for target 'tests/CMakeFiles/test_suites.dir/all' failed
make[1]: *** [tests/CMakeFiles/test_suites.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by mocchira** [comment]
@getong Thanks. I've found the bug that can cause cmake not to find subunit dependency and fixed it with https://github.com/leo-project/libcutil/commit/a4f844d0037d290f5eee10ec53fdb53c92f40493. Please check whether this commit works for you.

**Comment by getong** [comment]
@mocchira  bug remained. It is the test code error.
```
[ 50%] Built target cutil
Scanning dependencies of target test_suites
[ 58%] Building C object tests/CMakeFiles/test_suites.dir/main.c.o
[ 66%] Building C object tests/CMakeFiles/test_suites.dir/check_cache.c.o
[ 75%] Building C object tests/CMakeFiles/test_suites.dir/check_hashmap.c.o
[ 83%] Building C object tests/CMakeFiles/test_suites.dir/check_slab.c.o
[ 91%] Building C object tests/CMakeFiles/test_suites.dir/check_lru.c.o
[100%] Linking C executable test_suites
/usr/lib/gcc/x86_64-linux-gnu/6/../../../x86_64-linux-gnu/libcheck.a(check_log.o): In function `subunit_lfun':
(.text+0x5f4): undefined reference to `subunit_test_start'
/usr/lib/gcc/x86_64-linux-gnu/6/../../../x86_64-linux-gnu/libcheck.a(check_log.o): In function `subunit_lfun':
(.text+0x6bf): undefined reference to `subunit_test_fail'
/usr/lib/gcc/x86_64-linux-gnu/6/../../../x86_64-linux-gnu/libcheck.a(check_log.o): In function `subunit_lfun':
(.text+0x6d4): undefined reference to `subunit_test_pass'
/usr/lib/gcc/x86_64-linux-gnu/6/../../../x86_64-linux-gnu/libcheck.a(check_log.o): In function `subunit_lfun':
(.text+0x6ef): undefined reference to `subunit_test_error'
collect2: error: ld returned 1 exit status
tests/CMakeFiles/test_suites.dir/build.make:200: recipe for target 'tests/test_suites' failed
make[2]: *** [tests/test_suites] Error 1
CMakeFiles/Makefile2:140: recipe for target 'tests/CMakeFiles/test_suites.dir/all' failed
make[1]: *** [tests/CMakeFiles/test_suites.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by mocchira** [comment]
@getong Can you share the result of the below snippet?

```bash
## at the libcutil root directory
mkdir build && cd build
cmake ..
find . -type f |xargs grep subunit
```

**Comment by getong** [comment]
```
./CMakeCache.txt:_CHECK_LDFLAGS:INTERNAL=-lcheck_pic;-pthread;-lrt;-lm;-lsubunit
./CMakeCache.txt:_CHECK_LIBRARIES:INTERNAL=check_pic;rt;m;subunit
./CMakeCache.txt:_CHECK_STATIC_LDFLAGS:INTERNAL=-lcheck_pic;-pthread;-lrt;-lm;-lsubunit
./CMakeCache.txt:_CHECK_STATIC_LIBRARIES:INTERNAL=check_pic;rt;m;subunit
```

**Comment by getong** [comment]
I found the reason is the test code, you should check what is changed in my pr.  The test code not found the `subunit`, not the driver code.

**Comment by mocchira** [comment]
@getong Thanks. a few additional questions. 
- Do you have pkg-config installed on the build env?
- Where are the include files for subunit placed? (eg: /usr/include/subunit
- Where is the library file for subunit placed? (eg: /usr/lib/x86_64-linux-gnu/libsubunit.so

**Comment by mocchira** [comment]
> I found the reason is the test code, you should check what is changed in my pr. The test code not found the subunit, not the driver code.

I know about it. the linker flag should automatically be added even in case of the test code.

**Comment by mocchira** [comment]
@getong `find . -type f |xargs grep subunit` should output kind of the following if cmake can find the subunit.

```bash
./tests/CMakeFiles/test_suites.dir/link.txt:/usr/bin/cc     CMakeFiles/test_suites.dir/main.c.o CMakeFiles/test_suites.dir/check_cache.c.o CMakeFiles/test_suites.dir/check_hashmap.c.o CMakeFiles/test_suites.dir/check_slab.c.o CMakeFiles/test_suites.dir/check_lru.c.o  -o test_suites -rdynamic -Wl,-Bstatic -lcheck -Wl,-Bdynamic -lsubunit ../src/libcutil.a -lm -lpthread -lrt
./tests/CMakeFiles/test_suites.dir/DependInfo.cmake:  "/usr/include/subunit"
./tests/CMakeFiles/test_suites.dir/build.make:tests/test_suites: /usr/lib/x86_64-linux-gnu/libsubunit.so
./tests/CMakeFiles/test_suites.dir/flags.make:C_INCLUDES = -I/usr/include/subunit -I/home/leofs/dev/libcutil/tests/. -I/home/leofs/dev/libcutil/tests/../src
```

**Comment by getong** [comment]
@mocchira  
```
➜  build git:(develop) find . -type f |xargs grep subunit 
./CMakeCache.txt:_CHECK_LDFLAGS:INTERNAL=-lcheck_pic;-pthread;-lrt;-lm;-lsubunit
./CMakeCache.txt:_CHECK_LIBRARIES:INTERNAL=check_pic;rt;m;subunit
./CMakeCache.txt:_CHECK_STATIC_LDFLAGS:INTERNAL=-lcheck_pic;-pthread;-lrt;-lm;-lsubunit
./CMakeCache.txt:_CHECK_STATIC_LIBRARIES:INTERNAL=check_pic;rt;m;subunit
```
no other info found.

**Comment by mocchira** [comment]
@getong Please check the comment here: https://github.com/leo-project/libcutil/pull/4#issuecomment-322957726 to validate my assumption that you have NOT pkg-config installed and also placed include files/library file for subunit at somewhere else the current cmake script expects (ex. /usr/lib, /usr/local/lib, /opt/local/lib, /sw/lib). 

If my assumption is true, we'd consider adding the default search path for library/include files at

- https://github.com/leo-project/libcutil/blob/develop/CMakeModules/FindSubunit.cmake#L31-L34
- https://github.com/leo-project/libcutil/blob/develop/CMakeModules/FindSubunit.cmake#L42-L45

for the environment without pkg-config installed.

**Comment by getong** [comment]
```
➜  src which pkg-config
/usr/bin/pkg-config
➜  src ls /usr/include/subunit 
child.h
➜  src ls /usr/lib/x86_64-linux-gnu/libsubunit.so
/usr/lib/x86_64-linux-gnu/libsubunit.so
```

**Comment by getong** [comment]
The reference above is ubuntu 16.04, and mine is debian 9 stretch. I think they are the same env.

**Comment by mocchira** [comment]
@getong Thanks for sharing. It seems my guess is false so that means cmake should work as expected (detect subunit locations and add the linker flag) however actually doesn't on your env. That said, there might be some env differences between mine and yours or unknown bugs in the current cmake script so I'd like to vet further.

**Comment by mocchira** [comment]
@getong I've probably found the culprit.

In the current cmake cscript,
https://github.com/leo-project/libcutil/commit/24ff2cee0d45103a3417fa63ee88857cf8c0d460
We have this code in order to determine the linux distribution ID and its version on the build env. Since we add the linker flag for subunit only if the distribution ID == "ubuntu" and its version == "16.04", that obviously doesn't work on debian 9 stretch.

I'm going to add the implementation for dealing with debian 9 stretch properly.

**Comment by mocchira** [comment]
@getong I hope https://github.com/leo-project/libcutil/commit/8f75fc03087ea1820c7ec6a342a3bbd02be14613 will work for you. if it doesn't work then please tell me the result of `mkdir build && cd build && cmake ..`. The below snippet is on my dev env.

```
-- The C compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1")
-- Checking for module 'check'
--   Found check, version 0.10.0
-- Found Check: /usr/lib/x86_64-linux-gnu/libcheck.a
-- Linux distro is: Ubuntu 16.04 xenial
-- Checking for module 'subunit'
--   No package 'subunit' found
-- Found Subunit: /usr/lib/x86_64-linux-gnu/libsubunit.so
-- Configuring done
-- Generating done
-- Build files have been written to: /home/leofs/dev/libcutil/build
```
What I want to know is `-- Linux distro is: Ubuntu 16.04 xenial` this line on your env. Now I'd expect
- distro: Debian
- codename: stretch

if something different is shown, let me know.

**Comment by getong** [comment]
It works.

**Pull request closed without merging**
